#!/bin/bash
## Users must have sudo rights to use this file to deploy to users other then themselves.

tmp=$(echo "$@"|grep -Eo '(-u|--user)=[A-Za-z0-9_\-]+'| grep -Eo '=[A-Za-z0-9_\-]+'|grep -Eo '[A-Za-z0-9_\-]+')
[ -n "$tmp" ] && ssh_user=$tmp || ssh_user=$USER;

tmp=$(echo "$@"|grep -Eo '(-U|--tgt_user)=[A-Za-z0-9_\-]+'| grep -Eo '=[A-Za-z0-9_\-]+'|grep -Eo '[A-Za-z0-9_\-]+')
[ -n "$tmp" ] && tgt_user=$tmp || tgt_user=$USER;

tmp=$(echo "$@"|grep -Eo '(-k|--key)=([A-Za-z0-9_./-]+|"[A-Za-z0-9\\ _./-]+")'| grep -Eo '=([A-Za-z0-9_./-]+|"[A-Za-z0-9\\ _./-]+")'|grep -Eo '([A-Za-z0-9_\\ ./-]+)')
[ -n "$tmp" ] && keyfile="$tmp" || keyfile="$HOME/.ssh/id_rsa.pub";

tmp=$(echo "$@"|grep -Eo '(-H|--host)=([A-Za-z0-9_\/\.-]+|".+")'| grep -Eo '=([A-Za-z0-9_\/\.-]+|".+")'|grep -Eo '([A-Za-z0-9_\/\.-]+|".+")')
[ -n "$tmp" ] && host=$tmp || host='';

tmp=$(echo "$@"|grep -Eo '(-o|--opts)=([A-Za-z0-9_\/\-\.]+|".+")'| grep -Eo '=([A-Za-z0-9_\/\-\.]+|".+")'|grep -Eo '([A-Za-z0-9_\/\-\.]+|".+")')
[ -n "$tmp" ] && id_cmd=$tmp || id_cmd='';

tmp=$(echo "$@"|grep -Eo '(--controlfile)=([~A-Za-z0-9_./@:%-]+|"[~A-Za-z0-9\\ _./@:%-]+")'| grep -Eo '=([~A-Za-z0-9_./@:%-]+|"[~A-Za-z0-9\\ _./@:%-]+")'|grep -Eo '([~A-Za-z0-9_\\ ./:@%-]+)')
[ -n "$tmp" ] && control=$tmp || control='false';

tmp=$(echo "$@"|grep -Eo '(-s|--sudo)')
[ -n "$tmp" ] && sudo='sudo' || sudo='';

tmp=$(echo "$@"|grep -Eo '(-h|--help)')
[ -n "$tmp" ] && help='true' || help='';

tmp=$(echo "$@"|grep -Eo '(-D|--delete)')
[ -n "$tmp" ] && delete='true' || delete='false';

tmp=$(echo "$@"|grep -Eo '(-M|--master)')
[ -n "$tmp" ] && master='true' || master='false';

tmp=$(echo "$@"|grep -Eo '(-c|--create)')
[ -n "$tmp" ] && create='true' || create='false';

tmp=$(echo "$@"|grep -Eo '(--authkeys2)')
[ -n "$tmp" ] && authkeys='authorized_keys2' || authkeys='authorized_keys';


function usage {
echo -e "$1\n\nUsage: ssh-key-distrib -H|--host=example.com [-u|--user=user -U|--tgt_user=TargetUser -k|--key=keyfile -o|--opts=\"ssh options\" -s|--sudo"
echo -e '-H,--host\tSpecify the host to copy key to.
-u,--user\tSpecify the user to connect as.
-U,--tgt_user\tSpecify the target user on the host system.
-k,--key\tSpecify the keyfile to read and copy to $authkeys on the host. Paths with spaces should be formated like \"/Path\ To\ File/\".
-M,--master\tThis is a master key not a public one.
-o,--opts\tAdd extra ssh options here.
-s,--sudo\tUse sudo on the server side to copy keys to alternate user(-u user must have sudo on host.)
-D,--delete\tDelete key from specified host.
-c,--create\tCreate user if it does not exist.
  ,--control-file\tUse a control file for the connections.
  ,--authkeys2 [true|false]
-h,--help\tThis help message.';
exit 1;
}

[ -n "$help" ] && usage || t=1;

if [ -z "$host" ]; then
  usage "Error: -H|--host is required"
fi

if [ "$sudo" == 'sudo' ] && [ "$tgt_user" != "$ssh_user" ]; then
  sudo_cmd="sudo -u $tgt_user";
  id_cmd="$id_cmd -t -q"
else
  sudo_cmd='';
fi

ssh_cmd="ssh";

if [ "$control" == 'true' ]; then
    control='_key_distrib-%r@%h:%p';
    ssh_cmd="$ssh_cmd -S ~/.ssh/$control";
elif [ "$control" == 'false' ]; then
    echo '';
else
    ssh_cmd="$ssh_cmd -S $control";
fi


# load key into $key
if [ "$master" == 'true' ]; then
  if [ $(echo "$kefile" | grep -q '.pub') $? -eq 1 ] && [ -f "$keyfile" ]; then
    key=$(cat "$keyfile");
  fi
else
  if [ $(echo "$keyfile" | grep -q '.pub') $? -eq 0 ] && [ -e $keyfile ]; then
    key=$(cat $keyfile);
  elif [ -e "$keyfile.pub" ]; then
    key=$(cat "$keyfile.pub");
  else
    echo "Can't find keyfile for $keyfile";
    exit 1;
  fi
fi

if [ "$delete" == 'true' ]; then
  #delete mode
  if [ "$master" == 'true' ]; then
    keyname=$(basename $keyfile);
    $ssh_cmd $id_cmd $ssh_user@$host "$sudo_cmd bash -c 'rm ~$tgt_user/.ssh/$keyname'"
    echo "Removed key $keyname in $tgt_users .ssh/ directory";
    grep -v  "$keyname $host private(master)" ~/.ssh/deployed_keys > ~/.ssh/deployed_keys
  else
    $ssh_cmd $id_cmd $ssh_user@$host "$sudo_cmd /bin/bash -c '[ -f ~$tgt_user/.ssh/$authkeys ] && exit 0 || exit 1'";
    if [ $? -gt 0 ]; then
      echo "No $authkeys file for user ~$tgt_user";
    else
    ## this line assumes bash on the target machine.
      cmd="LINES=\$(grep -n \"$key\" ~$tgt_user/.ssh/$authkeys | grep -Ev \"[0-9]+:#\"|grep -oE \"^[0-9]+\");
LINES=\$(echo -e \$LINES | tr \"\n\" \";\" | sed \"s/;$//\");
sed -i \"\${LINES}d\" ~$tgt_user/.ssh/$authkeys";
      $ssh_cmd $id_cmd $ssh_user@$host "$sudo_cmd bash -c '$cmd'"
      echo "Removed entry in $tgt_user's .ssh/$authkeys file";
      grep -v "$keyfile $host public" ~/.ssh/deployed_keys > ~/.ssh/deployed_keys
      exit 0;
    fi
  fi
else
  [ "$create" == 'true' ] && [ "$tgt_user" != "$ssh_user" ] && c_user="[ \$(grep -q '^$tgt_user' /etc/passwd) \$? -ne 0 ] && adduser $tgt_user --ingroup admin; " || c_user='';

  [ "$create" == 'true' ] && [ "$tgt_user" != "$ssh_user" ] && c_cmd='-T' || c_cmd='';
  ## needs testing
  $ssh_cmd $id_cmd $ssh_user@$host "$sudo_cmd /bin/bash -c '$c_user[ -d ~$tgt_user/.ssh ] && echo -n '' || mkdir ~$tgt_user/.ssh'";
  ## needs testing
  if [ "$master" == 'true' ]; then
  #master key copy
    keyname=$(basename $keyfile);
    $ssh_cmd $id_cmd $ssh_user@$host "$sudo_cmd /bin/bash -c 'echo \"$key\" > ~$tgt_user/.ssh/$keyname;chmod 600 ~$tgt_user/.ssh/$keyname;'";
    echo "Added private(master) key \"$keyname\" in $tgt_user's .ssh/ directory";
    echo "$keyfile $host private(master)" >> ~/.ssh/deployed_keys
  else
    $ssh_cmd $id_cmd $ssh_user@$host "$sudo_cmd /bin/bash -c 'touch ~$tgt_user/.ssh/$authkeys;[ \`grep -q \"$key\" ~$tgt_user/.ssh/$authkeys\` \$? -ne 0 ] && echo \"$key\" >> ~$tgt_user/.ssh/$authkeys && chmod 740 ~$tgt_user/.ssh && chmod 600 ~$tgt_user/.ssh/$authkeys && chown -R $tgt_user ~$tgt_user/.ssh'";
    echo "Added public key entry in $tgt_user's .ssh/$authkeys file.";
    echo "$keyfile $host public" >> ~/.ssh/deployed_keys
  fi
fi

# ssh $id_cmd $ssh_user@$host "$sudo_cmd /bin/bash -c 'cat ~$tgt_user/.ssh/$authkeys'";
